# Generated by Django 4.1.5 on 2023-06-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="decription",
            new_name="description",
        ),
    ]
